/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VehiclesImport } from './routes/vehicles'
import { Route as TasksImport } from './routes/tasks'
import { Route as RegisterImport } from './routes/register'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as InformationImport } from './routes/information'
import { Route as DriversImport } from './routes/drivers'
import { Route as ClientsImport } from './routes/clients'
import { Route as IndexImport } from './routes/index'
import { Route as LogsVehiclesImport } from './routes/logs/vehicles'
import { Route as LogsTasksImport } from './routes/logs/tasks'
import { Route as LogsDriversImport } from './routes/logs/drivers'
import { Route as LogsClientsImport } from './routes/logs/clients'

// Create/Update Routes

const VehiclesRoute = VehiclesImport.update({
  path: '/vehicles',
  getParentRoute: () => rootRoute,
} as any)

const TasksRoute = TasksImport.update({
  path: '/tasks',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const InformationRoute = InformationImport.update({
  path: '/information',
  getParentRoute: () => rootRoute,
} as any)

const DriversRoute = DriversImport.update({
  path: '/drivers',
  getParentRoute: () => rootRoute,
} as any)

const ClientsRoute = ClientsImport.update({
  path: '/clients',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LogsVehiclesRoute = LogsVehiclesImport.update({
  path: '/logs/vehicles',
  getParentRoute: () => rootRoute,
} as any)

const LogsTasksRoute = LogsTasksImport.update({
  path: '/logs/tasks',
  getParentRoute: () => rootRoute,
} as any)

const LogsDriversRoute = LogsDriversImport.update({
  path: '/logs/drivers',
  getParentRoute: () => rootRoute,
} as any)

const LogsClientsRoute = LogsClientsImport.update({
  path: '/logs/clients',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsImport
      parentRoute: typeof rootRoute
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversImport
      parentRoute: typeof rootRoute
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksImport
      parentRoute: typeof rootRoute
    }
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesImport
      parentRoute: typeof rootRoute
    }
    '/logs/clients': {
      id: '/logs/clients'
      path: '/logs/clients'
      fullPath: '/logs/clients'
      preLoaderRoute: typeof LogsClientsImport
      parentRoute: typeof rootRoute
    }
    '/logs/drivers': {
      id: '/logs/drivers'
      path: '/logs/drivers'
      fullPath: '/logs/drivers'
      preLoaderRoute: typeof LogsDriversImport
      parentRoute: typeof rootRoute
    }
    '/logs/tasks': {
      id: '/logs/tasks'
      path: '/logs/tasks'
      fullPath: '/logs/tasks'
      preLoaderRoute: typeof LogsTasksImport
      parentRoute: typeof rootRoute
    }
    '/logs/vehicles': {
      id: '/logs/vehicles'
      path: '/logs/vehicles'
      fullPath: '/logs/vehicles'
      preLoaderRoute: typeof LogsVehiclesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  ClientsRoute,
  DriversRoute,
  InformationRoute,
  LoginRoute,
  ProfileRoute,
  RegisterRoute,
  TasksRoute,
  VehiclesRoute,
  LogsClientsRoute,
  LogsDriversRoute,
  LogsTasksRoute,
  LogsVehiclesRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/clients",
        "/drivers",
        "/information",
        "/login",
        "/profile",
        "/register",
        "/tasks",
        "/vehicles",
        "/logs/clients",
        "/logs/drivers",
        "/logs/tasks",
        "/logs/vehicles"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/clients": {
      "filePath": "clients.tsx"
    },
    "/drivers": {
      "filePath": "drivers.tsx"
    },
    "/information": {
      "filePath": "information.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/tasks": {
      "filePath": "tasks.tsx"
    },
    "/vehicles": {
      "filePath": "vehicles.tsx"
    },
    "/logs/clients": {
      "filePath": "logs/clients.tsx"
    },
    "/logs/drivers": {
      "filePath": "logs/drivers.tsx"
    },
    "/logs/tasks": {
      "filePath": "logs/tasks.tsx"
    },
    "/logs/vehicles": {
      "filePath": "logs/vehicles.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
